import mongoose, { Schema, Document } from 'mongoose'

export interface IAgent extends Document {
  userId: mongoose.Types.ObjectId
  agentId: string
  status: 'pending' | 'approved' | 'rejected' | 'suspended' | 'inactive' | 'disabled'
  commissionRate: number // Percentage (e.g., 5.5 for 5.5%)
  commissionType: 'percentage' | 'fixed' // percentage of service fee or fixed amount
  fixedCommissionAmount?: number // Used when commissionType is 'fixed'
  kycStatus: 'pending' | 'verified' | 'rejected'
  kycDocuments: {
    panCard?: string
    aadharCard?: string
    bankStatement?: string
    addressProof?: string
    photo?: string
  }
  bankDetails: {
    accountHolderName: string
    accountNumber: string
    ifscCode: string
    bankName: string
    branchName?: string
  }
  personalDetails: {
    fullName: string
    email: string
    phone: string
    address: string
    city: string
    state: string
    pincode: string
    dateOfBirth: Date
    emergencyContact: {
      name: string
      phone: string
      relation: string
    }
  }
  businessDetails: {
    businessName?: string
    businessType: 'individual' | 'partnership' | 'company'
    gstNumber?: string
    businessAddress?: string
    yearsOfExperience: number
    previousAgency?: string
  }
  performance: {
    totalApplications: number
    approvedApplications: number
    rejectedApplications: number
    totalCommissionEarned: number
    averageProcessingTime: number // in days
    clientSatisfactionRating: number // 1-5
  }
  settings: {
    emailNotifications: boolean
    smsNotifications: boolean
    commissionAlerts: boolean
    applicationUpdates: boolean
  }
  notes: string
  approvedBy: mongoose.Types.ObjectId
  approvedAt: Date
  lastLoginAt: Date
  isActive: boolean
  createdAt: Date
  updatedAt: Date
}

const AgentSchema = new Schema<IAgent>({
  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    unique: true
  },
  agentId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    uppercase: true
  },
  status: {
    type: String,
    enum: ['pending', 'approved', 'rejected', 'suspended', 'inactive', 'disabled'],
    default: 'disabled'
  },
  commissionRate: {
    type: Number,
    required: true,
    min: 0,
    max: 100
  },
  commissionType: {
    type: String,
    enum: ['percentage', 'fixed'],
    default: 'percentage'
  },
  fixedCommissionAmount: {
    type: Number,
    min: 0
  },
  kycStatus: {
    type: String,
    enum: ['pending', 'verified', 'rejected'],
    default: 'pending'
  },
  kycDocuments: {
    panCard: String,
    aadharCard: String,
    bankStatement: String,
    addressProof: String,
    photo: String
  },
  bankDetails: {
    accountHolderName: { type: String, required: true },
    accountNumber: { type: String, required: true },
    ifscCode: { type: String, required: true },
    bankName: { type: String, required: true },
    branchName: String
  },
  personalDetails: {
    fullName: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    address: { type: String, required: true },
    city: { type: String, required: true },
    state: { type: String, required: true },
    pincode: { type: String, required: true },
    dateOfBirth: { type: Date, required: true },
    emergencyContact: {
      name: { type: String, required: true },
      phone: { type: String, required: true },
      relation: { type: String, required: true }
    }
  },
  businessDetails: {
    businessName: String,
    businessType: {
      type: String,
      enum: ['individual', 'partnership', 'company'],
      default: 'individual'
    },
    gstNumber: String,
    businessAddress: String,
    yearsOfExperience: { type: Number, default: 0 },
    previousAgency: String
  },
  performance: {
    totalApplications: { type: Number, default: 0 },
    approvedApplications: { type: Number, default: 0 },
    rejectedApplications: { type: Number, default: 0 },
    totalCommissionEarned: { type: Number, default: 0 },
    averageProcessingTime: { type: Number, default: 0 },
    clientSatisfactionRating: { type: Number, default: 0, min: 0, max: 5 }
  },
  settings: {
    emailNotifications: { type: Boolean, default: true },
    smsNotifications: { type: Boolean, default: true },
    commissionAlerts: { type: Boolean, default: true },
    applicationUpdates: { type: Boolean, default: true }
  },
  notes: String,
  approvedBy: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedAt: Date,
  lastLoginAt: Date,
  isActive: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
})

// Indexes for better performance
// Note: userId and agentId indexes are automatically created due to unique: true
AgentSchema.index({ status: 1 })
AgentSchema.index({ kycStatus: 1 })
AgentSchema.index({ isActive: 1 })
AgentSchema.index({ createdAt: -1 })

// Generate agent ID before saving
AgentSchema.pre('save', async function() {
  if (!this.agentId) {
    try {
      const count = await mongoose.model('Agent').countDocuments()
      this.agentId = `AGT${String(count + 1).padStart(6, '0')}`
    } catch (error) {
      console.error('Error generating agent ID:', error)
      // Fallback to timestamp-based ID
      this.agentId = `AGT${Date.now().toString().slice(-6)}`
    }
  }
})

export default mongoose.models.Agent || mongoose.model<IAgent>('Agent', AgentSchema)
