import mongoose, { Document, Schema } from 'mongoose'

export interface IVisaApplication extends Document {
  userId: mongoose.Types.ObjectId
  visaId: string
  trackingId: string
  personalInfo: {
    firstName: string
    lastName: string
    email: string
    phone: string
    nationality: string
    occupation?: string
    passportNumber?: string
    passportExpiry?: Date
    purpose?: string
    startDate?: Date
    endDate?: Date
  }
  documents: {
    passport?: {
      url?: string
      publicId?: string
      originalName?: string
    }
    photo?: {
      url?: string
      publicId?: string
      originalName?: string
    }
    additionalInfo?: string
    additionalDocs?: Record<
      string,
      {
        url?: string
        publicId?: string
        originalName?: string
      }
    >
    // New agent-uploaded documents
    embassySubmissionProof?: {
      url: string
      publicId: string
      originalName: string
      uploadedBy: mongoose.Types.ObjectId
      uploadedAt: Date
    }
    embassyApprovalDocument?: {
      url: string
      publicId: string
      originalName: string
      uploadedBy: mongoose.Types.ObjectId
      uploadedAt: Date
    }
    embassyRejectionLetter?: {
      url: string
      publicId: string
      originalName: string
      uploadedBy: mongoose.Types.ObjectId
      uploadedAt: Date
    }
  }
  visaDetails: {
    country: string
    visaType: string
    price: number
    processingTime: string
    stayPeriod: string
    validity: string
  }
  status:
    | 'draft'
    | 'Pending' // booking created, payment not yet completed
    | 'Submitted' // payment succeeded
    | 'abandoned' // payment incomplete, moved after 15 minutes for lead generation
    | 'under_review'
    | 'assigned_to_agent'
    | 'in_embassy'
    | 'approved'
    | 'rejected'
    | 'completed'
    | 'cancelled'
  paymentStatus: 'pending' | 'completed' | 'failed'
  paymentMethod: 'cashfree' | 'stripe' | 'paypal' | 'upi' | 'card' | 'razorpay'
  paymentId?: string
  // Additional payment metadata captured during checkout or gateway callbacks
  paymentDetails?: {
    orderId?: string
    [key: string]: any
  }
  totalAmount: number
  convenienceFees: {
    onlineProcessing?: number
    paymentMethod?: number
    expressService?: number
    documentProcessing?: number
    total: number
  }
  baseAmount: number
  couponDiscount?: {
    couponCode?: string
    discountAmount: number
    discountType?: 'percentage' | 'fixed'
  }
  agentId?: mongoose.Types.ObjectId
  agentCommission?: {
    amount: number
    rate: number
    type: 'percentage' | 'fixed'
    status: 'pending' | 'approved' | 'paid' | 'cancelled'
  }
  notes?: string
  estimatedProcessingDate?: Date
  actualProcessingDate?: Date
  rejectionReason?: string
  statusHistory: {
    status: string
    changedBy: mongoose.Types.ObjectId
    changedByRole: 'user' | 'admin' | 'agent'
    changedByName: string
    timestamp: Date
    notes?: string
    reason?: string
  }[]
  // NEW: audit fields for auto-cleanup
  autoDeletedAt?: Date
  autoDeleteReason?: string
  // Fields for abandoned bookings (lead generation)
  abandonedAt?: Date
  abandonReason?: string
  // Email reminder flag
  paymentReminderSent?: boolean
}

const VisaApplicationSchema = new Schema<IVisaApplication>(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    visaId: {
      type: String,
      required: true,
      index: true,
    },
    trackingId: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      index: true,
    },
    personalInfo: {
      firstName: { type: String, required: true },
      lastName: { type: String, required: true },
      email: { type: String, required: true },
      phone: { type: String, required: true },
      nationality: { type: String, required: true },
      passportNumber: { type: String },
      passportExpiry: { type: Date },
      occupation: { type: String },
      purpose: { type: String },
      startDate: { type: Date },
      endDate: { type: Date },
    },
    documents: {
      passport: {
        url: { type: String },
        publicId: { type: String },
        originalName: { type: String },
        status: {
          type: String,
          enum: ['pending', 'approved', 'rejected', 'reuploaded'],
          default: 'pending',
        },
        rejectionReason: { type: String },
      },
      photo: {
        url: { type: String },
        publicId: { type: String },
        originalName: { type: String },
        status: {
          type: String,
          enum: ['pending', 'approved', 'rejected', 'reuploaded'],
          default: 'pending',
        },
        rejectionReason: { type: String },
      },
      additionalInfo: { type: String },
      additionalDocs: { type: mongoose.Schema.Types.Mixed, default: {} },
      // New agent-uploaded documents
      embassySubmissionProof: {
        url: { type: String },
        publicId: { type: String },
        originalName: { type: String },
        uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        uploadedAt: { type: Date },
      },
      embassyApprovalDocument: {
        url: { type: String },
        publicId: { type: String },
        originalName: { type: String },
        uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        uploadedAt: { type: Date },
      },
      embassyRejectionLetter: {
        url: { type: String },
        publicId: { type: String },
        originalName: { type: String },
        uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        uploadedAt: { type: Date },
      },
    },
    visaDetails: {
      country: { type: String, required: true },
      visaType: { type: String, required: true },
      price: { type: Number, required: true },
      processingTime: { type: String, required: true },
      stayPeriod: { type: String, required: true },
      validity: { type: String, required: true },
    },
    status: {
      type: String,
      enum: [
        'draft',
        'Pending', // booking created, payment not yet completed
        'Submitted', // payment succeeded
        'under_review',
        'assigned_to_agent',
        'in_embassy',
        'approved',
        'rejected',
        'completed',
        'cancelled',
      ],
      default: 'Pending',
      index: true,
    },
    paymentStatus: {
      type: String,
      enum: ['pending', 'completed', 'failed'],
      default: 'pending',
      index: true,
    },
    paymentMethod: {
      type: String,
      enum: ['cashfree', 'stripe', 'paypal', 'upi', 'card', 'razorpay'],
      required: true,
    },
    paymentId: { type: String },
    // Store arbitrary gateway/payment metadata (e.g., orderId)
    paymentDetails: { type: mongoose.Schema.Types.Mixed, default: {} },
    totalAmount: { type: Number, required: true },
    convenienceFees: {
      onlineProcessing: { type: Number, default: 0 },
      paymentMethod: { type: Number, default: 0 },
      expressService: { type: Number, default: 0 },
      documentProcessing: { type: Number, default: 0 },
      total: { type: Number, default: 0 },
    },
    baseAmount: { type: Number, required: true },
    couponDiscount: {
      couponCode: { type: String },
      discountAmount: { type: Number, default: 0 },
      discountType: { type: String, enum: ['percentage', 'fixed'] },
    },
    agentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Agent',
    },
    agentCommission: {
      amount: { type: Number, default: 0 },
      rate: { type: Number, default: 0 },
      type: { type: String, enum: ['percentage', 'fixed'] },
      status: {
        type: String,
        enum: ['pending', 'approved', 'paid', 'cancelled'],
        default: 'pending',
      },
    },
    notes: { type: String },
    estimatedProcessingDate: { type: Date },
    actualProcessingDate: { type: Date },
    rejectionReason: { type: String },
    statusHistory: [
      {
        status: { type: String, required: true },
        changedBy: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'User',
          required: true,
        },
        changedByRole: {
          type: String,
          enum: ['user', 'admin', 'agent'],
          required: true,
        },
        changedByName: { type: String, required: true },
        timestamp: { type: Date, default: Date.now },
        notes: { type: String },
        reason: { type: String },
      },
    ],
    // Audit fields for auto-cleanup (legacy - kept for backward compatibility)
    autoDeletedAt: { type: Date },
    autoDeleteReason: { type: String },
    // Fields for abandoned bookings (lead generation)
    abandonedAt: { type: Date },
    abandonReason: { type: String },
    paymentReminderSent: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
)

// Generate tracking ID before saving
VisaApplicationSchema.pre('save', async function() {
  if (!this.trackingId) {
    // Generate a unique tracking ID
    // Format: EU-YYMMDD-XXXX (EU = Euro, YYMMDD = Date, XXXX = Random string)
    const date = new Date()
    const dateStr = date.toISOString().slice(2, 10).replace(/-/g, '')
    const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase()
    this.trackingId = `EU-${dateStr}-${randomStr}`
  }
})

// Track status changes
VisaApplicationSchema.pre('save', function () {
  if (this.isModified('status') && !this.isNew) {
    // This will be populated by the calling function with proper user info
    if (!this.statusHistory) {
      this.statusHistory = []
    }
  }
})

// Ensure latest schema is used during Next.js dev hot-reload
if (
  process.env.NODE_ENV !== 'production' &&
  (mongoose.models as any).VisaApplication
) {
  delete (mongoose.models as any).VisaApplication
}
const VisaApplication = mongoose.model<IVisaApplication>(
  'VisaApplication',
  VisaApplicationSchema
)
export default VisaApplication
